name: Build iOS Flutter App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: iOS Build
    runs-on: macos-12

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Flutter dependencies
        run: flutter pub get
        working-directory: frontend

      - name: Build iOS App
        run: flutter build ios --release --no-codesign
        working-directory: frontend
